### ISSUE TITLE
Link to place from map gives 404

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto-comparador-presupuestos#167]
- Go to map https://presupuestos.gobierto.es/mapas/2018
- Click on a place
- Wrong URL - 404 

![imagen.png](https://images.zenhubusercontent.com/59da7a2db0222d5de47ac5ba/38870e88-5d7e-40c2-b96a-6ebf11d3fb7a)

**Comment by ferblape** [comment]
Fixed and released.
