### ISSUE TITLE
Avoid ajax requests to fill highlighted budget lines card

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto-comparador-presupuestos#186]
Highlighted budget lines card performs ajax requests to load these cards:

![Screen Shot 2019-03-18 at 10 55 59](https://user-images.githubusercontent.com/17616/54521987-733a3180-496c-11e9-898f-9e6ddbf73310.png)

We made the decision to make the code more reusable when we adopted Flight.js, which wasn't a good idea. Please, remove those calls and obtain that information from the controller itself.

After implementing this the load of the widget should feel smoother.

**Comment by amiedes** [comment]
Done in https://github.com/PopulateTools/gobierto-comparador-presupuestos/pull/189
