### ISSUE TITLE
Wrong date in the about page

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto-comparador-presupuestos#271]
In the [about page](https://presupuestos.gobierto.es/about#method) the data update date should be just the year, not the whole date:

![Screen Shot 2019-09-02 at 14 46 11](https://user-images.githubusercontent.com/17616/64115647-79905e80-cd90-11e9-909b-4002082f992b.png)

**Comment by amiedes** [comment]
Fixed by https://github.com/PopulateTools/gobierto-comparador-presupuestos/commit/c382052c4baecd3e18b505205fa301576bd73013

**Comment by amiedes** [comment]
For this to take effect in production the CDN cache needs to be purged. I've tried to do it but it's ignoring me.
