### ISSUE TITLE
Fix legend colors in budget lines graph

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto-comparador-presupuestos#67]
http://presupuestos.gobify.net/compare/salcedillo:mataro/2018/expense/functional

This was already done for Gobierto, so check the code there. Merge in the other comparator also.

**Comment by ferblape** [comment]
Fixed

**Comment by ferblape** [comment]
Still happening here: http://presupuestos.gobify.net/budget_lines/salcedillo/2013/76/I/economic

**Comment by ferblape** [comment]
fixed in 691b31bcf5176eb2552c8701042875fc82e13dcf
